name: New App Version

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: 'Release type (one of): patch, minor, major'
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Create New Version and push new tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Git User Setup
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: Bump version, push branch and create PR
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          BRANCH_NAME="release/${{ github.event.inputs.release-type }}-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME
          pnpm version ${{ github.event.inputs.release-type }} -m "chore(release): %s"
          NEW_VERSION=$(node -p "require('./package.json').version")
          git push origin $BRANCH_NAME --follow-tags
          gh pr create \
            --base master \
            --head $BRANCH_NAME \
            --title "chore(release): bump version to v$NEW_VERSION" \
            --body "Automated PR to update the application version to v$NEW_VERSION."
